SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

RECORDS_WINDOW_WIDTH = 1000
RECORDS_WINDOW_HEIGHT = 600

BUTTON_WIDTH = 200
BUTTON_HEIGHT = 70
BUTTON_SIZE = (BUTTON_WIDTH, BUTTON_HEIGHT)

TITLE = "Нашествие монстров"

# Показывать границы персонажей
SHOW_BORDERS = False

DB_PATH = './db.sqlite'
