
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

BUTTON_WIDTH = 200
BUTTON_HEIGHT = 70
BUTTON_SIZE = (BUTTON_WIDTH, BUTTON_HEIGHT)

TITLE = "Нашествие монстров"

# Показывать границы персонажей
SHOW_BORDERS = True
